### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by markthethomas** [sindresorhus/ava#167]
Has there been any thought/discussion to setting up a contributing guidelines doc? I know we've all seen them, but here are a few examples I've tended to like:
- [npm](https://github.com/npm/npm/wiki/Contributing-Guidelines)
- [babel](https://github.com/babel/babel/blob/master/CONTRIBUTING.md)
- [Contributor Code of Conduct](http://contributor-covenant.org/version/1/0/0/)

I've always appreciated having the behavioral/philosophical guidelines set out, but I think it's also important that the basics of `git clone`, `npm test` etc. are there. Maybe we just link to some `contributing.md` doc in the FAQ at the bottom of the readme?

**Comment by sindresorhus** [comment]
Not sure it's worth the time writing one. I've tried it with [awesome](https://github.com/sindresorhus/awesome/blob/master/contributing.md) and some other projects and after hundreds of pull requests, not even one person bothered to read it. I think the problem is that people that bothers to read a contribution guidelines are usually the kind of people that doesn't need to in the first place. That goes the other way too.

Relevant:
https://twitter.com/sindresorhus/status/655792500590923776
https://twitter.com/sindresorhus/status/620278511127953408

> but I think it's also important that the basics of git clone, npm test etc. are there

Why? I don't think every project should cover how to do generic and basic things like that.

-

Let's see what others think, but I'm generally pessimistic of the usefulness of a contributing.md.

**Comment by markthethomas** [comment]
Ah, bummer that people never do. But I guess that's the way of all documentation. 

I tend to like them because it gives me a sense of the project and how I might fit in etc., but it seems like that's just me :smile: Totally see your point about there being a mismatch in those who would need to read it and those who do. 

> > but I think it's also important that the basics of git clone, npm test etc. are there

> Why? I don't think every project should cover how to do generic and basic things like that.

Was just thinking with beginners (like myself) in mind :+1: Nothing I care deeply about — just something I've occasionally appreciated.

**Comment by Whoaa512** [comment]
It would be useful if Github allowed you to pre-populate PRs and issues. I've had [isaacs/github/#99](https://github.com/isaacs/github/issues/99) opened for over 2 years now and the best they can do is query string params :unamused:
