### ISSUE TITLE
index spec files fail

### ISSUE THREAD

**Issue by billyjanitsch** [sindresorhus/ava#224]
```js
// test/index.spec.js
import test from 'ava'

test('dummy', t => {
  t.end()
})
```

Running AVA on this file yields:
```
  ✔ test › index › dummy
Uncaught Exception:  /Users/billy/projects/ava-test/node_modules/deep-extend/test/index.spec.js
  Error: Cannot find module 'should'
    at Object.<anonymous> (/Users/billy/projects/ava-test/node_modules/deep-extend/test/index.spec.js:5:14)
    at requireFromString (/Users/billy/projects/ava-test/node_modules/require-from-string/index.js:26:4)
```

Appears to be an issue with `require-from-string`.

**Comment by vdemedes** [comment]
@floatdrop could you please confirm?

**Comment by jamestalmage** [comment]
The issue is not with `require-from-string`.

You have `deep-extend` installed, which ships with it's own `test/index.spec.js`, and that is getting picked up with whatever `grep` string you are using.

Maybe AVA should avoid picking up files in `node_modules`, even if their glob string says too.

https://github.com/unclechu/node-deep-extend/pull/21
 

```

➜  ava-test  ava

  ✔ dummy

  1 test passed

```

**Comment by billyjanitsch** [comment]
Ah, my mistake, thanks for clarifying!

**Comment by jamestalmage** [comment]
@billyjanitsch 
Were you using the default glob string, or specifying your own? We should probably prevent AVA from picking that sort of file up by default.

**Comment by billyjanitsch** [comment]
I was specifying my own, and forgot that it would pick up `node_modules`.

**Comment by jamestalmage** [comment]
happens to the best of us.

I opened #226 to discuss the possibility of protecting against this sort of mistake.
