### ISSUE TITLE
CLI `--debug` flag

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#31]
For running everything serially so it's easier to debug concurrency issues.

In the future it might do other things too to aid in debugging. Suggestions welcome.

**Comment by Qix-** [comment]
:+1:

**Comment by vdemedes** [comment]
Currently, ava does not have a single config store, so we have to come up with some way to share configuration between scripts. Right now, I can see 2 ways to implement this, without major code changes:

1. `ava --debug` sets environment variable, so that other scripts (files) see it: `process.env.AVA_DEBUG = true`. Also, it will be possible to enable debug mode by `AVA_DEBUG=true ava`.
2. Have a `config.js` with `module.exports = {}` and set config values there (all scripts that `require('./config')` will get the same object).

What do you think?

**Comment by vdemedes** [comment]
Config would also be handy for #27

**Comment by Qix-** [comment]
Do you mean for child processes? Or just for the AVA scripts in general?

**Comment by vdemedes** [comment]
@Qix- Sorry, did not understand your question

**Comment by Qix-** [comment]
I re-read your comment; I think see what you mean now.

I'd have to test, but I'd suspect that ad-hoc environment variables added to `process.env` would be passed down to child processes too, which means that's a plausible way of storing configuration so child AVA processes will be aware of configuration. Unless that's not how @sindresorhus plans on implementing child processes.

**Comment by vdemedes** [comment]
Yes, child processes will get modified `process.env` object (node.js docs say so).

**Comment by sindresorhus** [comment]
I don't understand how this is related to a `--debug` flag? Right now it doesn't use any child-processes, but just `require`'s the test files.

As for sharing config with sub-processes, that's better discussed in #1. But tl;dr, `child_process.fork` and message passing.

**Comment by vdemedes** [comment]
@sindresorhus I was talking about the ways to indicate, that user specified `--debug` flag and wants tests to run serially. For example, as for now, how would `lib/test.js` know, that `cli.js` has `debug = true`?

**Comment by sindresorhus** [comment]
It could just read argv: `process.argv.indexOf('--debug') !== -1`. But more likely the CLI will pass it as an option to the `lib/test.js` interface.
