### ISSUE TITLE
Don't use `regenerator` in `babel-preset-es2015` for newer Node.js versions

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ava#348]
Split out of https://github.com/sindresorhus/ava/pull/333.

Only Node.js 0.10 needs `regenerator`, but it's currently included for any Node.js version.

Someone needs to do a pull request to [`babel-preset-es2015`](https://github.com/babel/babel/tree/master/packages/babel-preset-es2015) and [auto-detect generator support](https://github.com/sindresorhus/has-generator) and conditionally include `regenerator` (preferred solution) or add an option for toggling `regenerator`.

// @thejameskyle @jamestalmage

**Comment by thedev** [comment]
What do you think about using a post install script ?
Noticed the following discussion: https://github.com/npm/npm/issues/7340

**Comment by sindresorhus** [comment]
@thedev This isn't about having `regenerator` as a dependency. We just don't want the runtime overhead of using `regenerator` when it's not needed for newer Node.js versions which supports generators.

**Comment by thejameskyle** [comment]
> Someone needs to do a pull request to babel-preset-es2015 and auto-detect generator support and conditionally include regenerator (preferred solution) or add an option for toggling regenerator.

The Babel preset would not accept a pull request for that, just because the environment that is running Babel supports generators does not mean the targeted environment will.

If you want to create a preset `babel-preset-node-feature-detection` that tests for support for everything before running it, that would likely be the best solution. However, it should warn heavily that you should not distribute the generated code with it (we don't want npm filled with node version specific modules).

**Comment by sindresorhus** [comment]
@thejameskyle That's a good point. I just considered our case of live transpiling. Would you be open to add an option to the preset for toggling `regenerator`? We really don't want to have to maintain our own presets.

**Comment by thejameskyle** [comment]
https://phabricator.babeljs.io/T2756

**Comment by ariporad** [comment]
@sindresorhus: Check out [hax/babel-features](https://github.com/hax/babel-features). I'll turn it into a preset if you want. Or we could just use it directly.

**Comment by ariporad** [comment]
@sindresorhus: Actually, I went ahead and turned that into a preset anyway: [`babel-preset-features`](npm.im/babel-preset-features). It's a drop-in replacement for `babel-preset-e2015`, I'll submit a PR.

**Comment by tmaximini** [comment]
I ran into the same issue, went with https://github.com/alekseykulikov/babel-preset-es2015-node5 for now

**Comment by jamestalmage** [comment]
@tmaximini What issue? The only difference should be one of performance. If you've got other issues let us know.

**Comment by novemberborn** [comment]
Closing in favor of #148.

**Comment by buzinas** [comment]
@jamestalmage performance always matters, and it's always good to have as much as possible a generated code side-by-side with the source one.

If we have native support, we should always use it, there is absolutely no reason to use something ugly and gross on top of something that already exists and performs well.

I can understand people using bluebird instead of the native Promise, for example, but using a feature like regenerator, only if targeting browsers.

Another great difference: Debugging is terrible with regenerators, and it's awesome with native generators.
