### ISSUE TITLE
Clean up redundant assertion error output. 

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/ava#422]
Currently the following:

```js
test(t => t.ok(false))
```

Will log the following:

```
false == true
AssertionError: false == true
  ... remaining stack-trace ...
```

This is redundant.

It only happens for enhanced assertions.

I think the solution could be as simple as: `err.message + stripFirstLine(err.stack)`.

**Comment by sindresorhus** [comment]
Note to self: Update screenshot (https://github.com/sindresorhus/ava/pull/428) when this is done.

**Comment by naptowncode** [comment]
Just to clarify, the intent is to lose the `AssertionError: false == true` line?

**Comment by sindresorhus** [comment]
@naptowncode Correct.

**Comment by naptowncode** [comment]
I tried just stripping the first line of the stack trace but @vdemedes pointed out that it would prevent telling the difference between different types of errors. I see two possibilities:

1. Just use `err.stack` without `err.message`, since the message will be in the first line of the stack trace anyway, or
2. A special case that strips the first line of the stack trace only for an `AssertionError`. This isn't my first choice but I see there is already a special case for `AssertionError` in `Api._handleTest()`.
