### ISSUE TITLE
TAP: Which specification should be adhered to?

### ISSUE THREAD

**Issue by therealklanni** [sindresorhus/ava#473]
I can't find anything in the [TAP spec](https://testanything.org/tap-version-13-specification.html) that suggests/implies that printing out a "# tests N" summary is within specification. Should it be removed it from TAP output?

Following the discussion below, I think this is more of a discussion about which version of TAP output should AVA generate?

**Comment by jamestalmage** [comment]
I believe @vdemedes modeled our output after `node-tap` (which I believe uses the draft v14 spec)

**Comment by vdemedes** [comment]
Yeah, I think I used tap or tape when building TAP support into AVA.

**Comment by therealklanni** [comment]
Oh, so why does it print "TAP version 13"? ;)

**Comment by jamestalmage** [comment]
I believe v14 is backward compatible in most ways. Any additions were done as comment directives. `node-tap` still prints v13 because v14 isn't officially recognized yet. But `tap-mocha-reporters` recognize many v14 directives.

As I recall the v14 draft was born from the extensions `node-tap` added to the spec.

**Comment by therealklanni** [comment]
I couldn't find anything about v14, can you post a link?

**Comment by jamestalmage** [comment]
https://github.com/TestAnything/testanything.github.io/pull/36

**Comment by sindresorhus** [comment]
@isaacs Seems your PR https://github.com/TestAnything/testanything.github.io/pull/36 has been open for a while. What would it take to get it merged? Anything we can help with?

**Comment by therealklanni** [comment]
Thanks for the link

**Comment by therealklanni** [comment]
I think we should also take into consideration that if we're going to use a draft specification, the TAP output that AVA produces will likely break most reporters in some way. I would be more comfortable with sticking to v13, personally, because I want to use tools that are available today and not have to wait for things to get updated to v14 (which as @sindresorhus points out has been sitting in discussion for several months).

**Comment by jamestalmage** [comment]
> the TAP output that AVA produces will likely break most reporters in some way

Not really. We are following the output of the two most popular tap producing libraries on Node (`node-tap` and `tape`). From the first line of that PR:

> [v14] seeks to ratify existing behavior of TAP harnesses and producers

In other words - codify the existing reality.

> it stands to reason that v14 will be backwards compatible to v13, but not the other way around

Not really. v14 output should be interpreted just fine by v13 consumers (though perhaps not as pretty as it could).

**Comment by therealklanni** [comment]
Well, I said that based on the fact that other reporters like faucet seem to get confused in certain situations (maybe it's just an opportunity to get faucet up to v14 spec, then, and any others that can't parse the newer spec output can probably be considered edge cases). I'm fine with whatever the consensus is, just wanted to open the discussion. Thanks for the input. :grinning:

**Comment by jamestalmage** [comment]
> maybe it's just an opportunity to get faucet up to v14 spec

It's been 2 years since a faucet release. That it works at all is a testament to good backward compatible design built in to the TAP protocol.

That said - if the problem is just the `# tests N` line, that could be removed. (Though I think that's actually something we emulated from `tape` instead of the spec - so it is a bit weird it doesn't work with `faucet` as it's from the same author).

**Comment by therealklanni** [comment]
That in particular "works" (in the sense that it just ignores it and doesn't suppress the line).

**Comment by isaacs** [comment]
We (and by that I mean, mostly *I*) need to get back to pushing TAP 14 over the finish line.  There were some good bits of feedback from the last round of comment on the PR, and I just haven't gotten around to incorporating them yet.  I should probably spend more time on the spec, and a little bit less on node-tap, I suppose, but when I'm not doing my "real" job, I try to just let the spirit guide me :)

At the current state of things, the latest and greatest versions of node-tap, prove, and Test::More are pretty much in alignment.

The reason why node-tap's output says "TAP version 13" is because the TAP 13 spec requires it!  However, TAP is a very "anything goes" protocol, so the other stuff like nested tests and such is pretty ambiguous.  Anything that is prefixed by whitespace that isn't yaml *should* be ignored by a consumer, so that's why child tests work.  If you're not down with them, you just get the roll-up, and it's less informative, but not *incorrect*.  (Even the idea of whether `# 4 tests, 2 pass` is a "comment" or a "directive" is very unclear, but it *is* clear that consumers should do nothing with it.)

I'd recommend, especially in the JavaScript world, to follow the not-yet-fully-birthed TAP14 specification.  What you actually print on the version line is mostly irrelevant.

**Comment by therealklanni** [comment]
Thanks @isaacs
