### ISSUE TITLE
Test-like output when test file does not exist

### ISSUE THREAD

**Issue by vdemedes** [sindresorhus/ava#575]
The output is not what it should look like (latest master):

```
$ ava example.js
```

(example.js does not exist).

<img width="315" alt="screen shot 2016-02-28 at 1 46 21 pm" src="https://cloud.githubusercontent.com/assets/697676/13379285/c960aef4-de21-11e5-90d0-eee4ea62e640.png">

First of all, notice 1 extra line at the start & end of the output. And top-level CLI errors should be displayed as:

```

  ❎ Couldn't find any files to test

```

**Comment by novemberborn** [comment]
This is probably due to <https://github.com/novemberborn/ava/commit/9dd03d5d2b20de48e72cb59e29573dd412201b1b> (see #502). There's some variance between the reporters, looks like the verbose one should render a cross.

Maybe this particular exception should be treated differently in the mini reporter. Or perhaps a general case can be made when there is 1 exception and no tests where found.

**Comment by vdemedes** [comment]
No no, this kind of top-level output from CLI should be written without reporters, as those are fatal errors.

**Comment by novemberborn** [comment]
> No no, this kind of top-level output from CLI should be written without reporters, as those are fatal errors.

Not when watching though. It's legit to start a watcher even if there are no test files yet. Or to remove the only test file while the watcher is running.

**Comment by sotojuan** [comment]
What's the status of this? A simple edit to `reporters/mini.js` fixes the extra lines, but what about the cross? Also an easy fix in the reporter file.

**Comment by novemberborn** [comment]
If we can agree that these are not fatal errors then I think we can fix up the reporters.

**Comment by sotojuan** [comment]
Closing because this was fixed a while back in #704.
