### ISSUE TITLE
Output in watch mode should be less verbose

### ISSUE THREAD

**Issue by ben-eb** [sindresorhus/ava#670]
## Description

I like the watch mode so far, but I think its verbosity could be reduced. Using the default reporter, the output is this:

<img width="391" alt="screen shot 2016-03-22 at 10 51 11" src="https://cloud.githubusercontent.com/assets/1282980/13958825/7fcba71e-f049-11e5-8cd1-ec92e6ddbe9b.png">

A good solution to this would be to print less empty lines; but my ideal solution would be that these messages should not show at all. Instead, it would be really great if it showed simply a wait cursor, and only printed a message when a test fails.

## Environment

```
Node.js v5.4.1
darwin 15.0.0
```

**Comment by sindresorhus** [comment]
@novemberborn Any reason we can't just overwrite the output like we do in the mini-reporter?

**Comment by jamestalmage** [comment]
> A good solution to this would be to print less empty lines;

:+1: 

> my ideal solution would be that these messages should not show at all

:-1: It is good to know it is still doing something (a simple spinner isn't reassuring enough). Also, you can technically also use this with the verbose reporter (`--watch --verbose`). 

> any reason we can't just overwrite the output

:+1: for doing that with the mini reporter. Verbose should just be an endless scroll.

-- 

We should also include some indicator that another test run has occurred. For small test suites it's already so fast that if you blink you might miss it (and you can't tell one `12 passed` line from the previous). I am thinking maybe a timestamp (light gray):

`[10:51:03] 12 passed`

**Comment by sindresorhus** [comment]
Timestamp would indeed be good for both default and verbose mode.

**Comment by novemberborn** [comment]
:+1: to overwrite the output, and the timestamp.

@ben-eb thanks for using watch mode!

**Comment by jfmengels** [comment]
Food for thought: In Mocha's watch mode, we get the time the tests took to run.
![image](https://cloud.githubusercontent.com/assets/3869412/14019348/a9ea7806-f1d2-11e5-95ed-fadbc37c1bf3.png)
I like this since you have early feedback about whether your tests are fast or not, since Mocha re-runs all tests every time. In AVA, only the tests for the saved file are re-run, but it might be a nice addition too.
I usually look at the time it took to see whether tests have re-run. Look at previous run time, save file, compare with run time, if it's different, it has run. :+1: on either the timestamp, the run time or both.
