### ISSUE TITLE
deepEqual doesn't throw when comparing { a: false } and { a: 0 }.

### ISSUE THREAD

**Issue by Enome** [sindresorhus/ava#772]
## Description

It seems that deepEqual uses the module [only-shallow](https://github.com/othiym23/only-shallow). 

In their readme they state:

> Use loose equality (==) only for value types (non-objects). This is the biggest difference between only-shallow and deeper / deepest. only-shallow cares more about shape and contents than type. 

So that's probably why false and 0 are considered equal.

## Environment

- Node.js v4.2.4
- linux 3.19.0-58-generic

I cloned the current master and verified by adding the following test to test/assert.js.

```js
t.throws(function () {
  assert.deepEqual({a: 0}, {a: false});
});
```

**Comment by novemberborn** [comment]
Yea, that sounds wrong. We'd want the structure to match, but also value types.

Maybe we should fork `only-shallow`… `not-that-shallow`? 😉

**Comment by sotojuan** [comment]
> Maybe we should fork only-shallow… not-that-shallow? 😉

I'm down for doing that—would it make sense to push it to npm or load it through GitHub? Feel silly publishing the same thing but with one extra `=`.

**Comment by jamestalmage** [comment]
> would it make sense to push it to npm or load it through GitHub? Feel silly publishing the same thing but with one extra =.

Definitely publish on `npm`. It's more than just one extra `=`. See [the source](https://github.com/othiym23/only-shallow/blob/master/index.js). You will also need to rewrite a portion of the tests to reflect the updated behavior.

I know @othiym23 has a number of these deep-equality comparison algorithms floating around. @othiym23 - Is there one that does what we are looking for? Basically `deeper` without recursing into the prototype or constructor? If not, it might be better to start with `deeper`, and eliminate [this line](https://github.com/othiym23/node-deeper/blob/master/index.js#L99)

**Comment by othiym23** [comment]
At this point, there's:

- `only-shallow`, which I made to match `tap`'s expectations of structural equality
- `deeper`, which I made to be like Node's built-in `deepEqual` / @substack's `deep-equal`, but with cycle-breaking and more strict prototype checking (largely because it seems absurd to me to have an identity test that says `[]` and `{}` are the same)
- `deepest`, which I made because it was fun to see how absurdly strict a structural equality test could be

So with the exception of `deepest`, these are purpose-built algorithms designed for specific purposes, which makes tweaking them unappealing (and, at least, a semver-major version bump). I'm not _super_ interested in writing another one, but it's A-OK if you want to use any of my code (which is largely cribbed from elsewhere anyway) as the basis for a new one for ava.

This makes me think that it might be interesting to create some kind of identity generator, where you use an options argument and the function constructor to dynamically generate a JITtable equality test that does _exactly_ what a given application requires, but I'm unlikely to have the time to hack on such a thing soon.

**Comment by sotojuan** [comment]
So I went into `node_modules/only-shallow`, switched out `==` with `===` and tested deep equality of `{a: false}` and `{a: 0}`—it failed as it should. Obviously, a bunch of `only-shallow` tests themselves failed but that seems easy to fix. I think we're good to go for our version (`not-so-shallow`!)—I'm more than willing to create it but there might be some edge cases I'm missing.

And thanks @othiym23 for the explanation!

**Comment by jamestalmage** [comment]
> largely because it seems absurd to me to have an identity test that says [] and {} are the same

Agreed - that seems ridiculous. Do we need to rethink the decision to drop `deeper`? Perhaps bump the priority for adding custom assertions so people have a viable workaround if `deeper` doesn't work for them?

**Comment by jamestalmage** [comment]
> This makes me think that it might be interesting to create some kind of identity generator, where you use an options argument and the function constructor to dynamically generate a JITtable equality test that does exactly what a given application requires, but I'm unlikely to have the time to hack on such a thing soon.

Interesting idea. What options should it have?
